
#O.S Por assundo
###
POST https://crm.tubaron.net/webservice/v1/su_oss_chamado
Authorization: Basic token
ixcsoft:listar
Content-Type: application/json

{
    "grid_param": "[{\"TB\":\"su_oss_chamado.id_assunto\", \"OP\" : \"IN\", \"P\" : \"1056,712\"},{\"TB\":\"su_oss_chamado.status\", \"OP\" : \"=\", \"P\" : \"F\"},{\"TB\":\"su_oss_chamado.data_abertura\", \"OP\" : \"BE\", \"P\" : \"2025-08-01 00:00:00\", \"P2\" : \"2025-08-08 23:59:59\"}]"
}

#Retorno
# {
#   "total": 25,
#   "registros": [
#     {
#       "id": "1019716",
#       "id_cliente": "36615",
#       "id_assunto": "1056",
#       "setor": "1",
#       "id_cidade": "4745",
#       "id_tecnico": "3521"
#     }
#   ]
# }

# em grid_params o valor \"1056,712\" precisar uma variavel e pode receber mais de um valor, esses id's vão vir da consulta O.S Por setor id_assunto, \"2025-08-01 00:00:00\", \"P2\" : \"2025-08-08 23:59:59\" tambem precisa ser uma variavel, e deve contar um filtro de data inicial e final na dashboard.


#O.S Por setor
###
POST https://crm.tubaron.net/webservice/v1/su_oss_chamado
Authorization: Basic token
ixcsoft:listar
Content-Type: application/json

{
    "grid_param": "[{\"TB\":\"su_oss_chamado.setor\", \"OP\" : \"=\", \"P\" : \"1\"},{\"TB\":\"su_oss_chamado.status\", \"OP\" : \"=\", \"P\" : \"F\"},{\"TB\":\"su_oss_chamado.data_abertura\", \"OP\" : \"BE\", \"P\" : \"2025-08-01 00:00:00\", \"P2\" : \"2025-08-08 23:59:59\"}]"

}

#Retorno
# {
#   "total": 127,
#   "registros": [
#     {
#       "id": "1019804",
#       "id_assunto": "1052",
#       "setor": "1",
#       "id_cidade": "4660",
#       "id_tecnico": "20"
#     }
#   ]
# }



#O.S Por colaborador
###
POST https://crm.tubaron.net/webservice/v1/su_oss_chamado
Authorization: Basic token
ixcsoft:listar
Content-Type: application/json

{
    "grid_param": "[{\"TB\":\"su_oss_chamado.id_tecnico\", \"OP\" : \"=\", \"P\" : \"3570\"},{\"TB\":\"su_oss_chamado.status\", \"OP\" : \"=\", \"P\" : \"F\"},{\"TB\":\"su_oss_chamado.data_abertura\", \"OP\" : \"BE\", \"P\" : \"2025-08-01 00:00:00\", \"P2\" : \"2025-08-08 23:59:59\"}]"
}

#Retorno
# {
#   "total": 31,
#   "registros": [
#     {
#       "id": "1019474",
#       "id_cliente": "38056",
#       "id_assunto": "1056",
#       "setor": "1",
#       "id_cidade": "4745",
#       "id_tecnico": "3570",
#     }
#   ]
# }

# em grid_params o valor \"3570\" precisar uma variavel e pode receber mais de um valor, esses id's vão vir da consulta O.S Por setor id_tecnico, \"2025-08-01 00:00:00\", \"P2\" : \"2025-08-08 23:59:59\" tambem precisa ser uma variavel, e deve contar um filtro de data inicial e final na dashboard.

#O.S Por cidade
###
POST https://crm.tubaron.net/webservice/v1/su_oss_chamado
Authorization: Basic token
ixcsoft:listar
Content-Type: application/json

{
  
    "grid_param": "[{\"TB\":\"su_oss_chamado.id_cidade\", \"OP\" : \"=\", \"P\" : \"4745\"},{\"TB\":\"su_oss_chamado.status\", \"OP\" : \"=\", \"P\" : \"F\"},{\"TB\":\"su_oss_chamado.data_abertura\", \"OP\" : \"BE\", \"P\" : \"2025-08-01 00:00:00\", \"P2\" : \"2025-08-08 23:59:59\"}]"
}

#Retorno
# {
#   "total": 208,
#   "registros": [
#     {
#       "id": "1019840",
#       "id_cliente": "36328",
#       "id_assunto": "14",
#       "setor": "5",
#       "id_cidade": "4745",
#       "id_tecnico": "3588"
#     }
#   ]
# }

# em grid_params o valor \"4745\" precisar uma variavel e pode receber mais de um valor, esses id's vão vir da consulta O.S Por setor id_cidade, \"2025-08-01 00:00:00\", \"P2\" : \"2025-08-08 23:59:59\" tambem precisa ser uma variavel, e deve contar um filtro de data inicial e final na dashboard.



# Assundo por ID
###
POST https://crm.tubaron.net/webservice/v1/su_oss_assunto
Authorization: Basic token
ixcsoft:listar
Content-Type: application/json

{
    "qtype": "su_oss_assunto.id",
    "query": "1056,14", 
    "oper": "IN",
    "page": "1",
    "op": "20"
}

#Retorno
# {
#   "page": "1",
#   "total": "2",
#   "registros": [
#     {
#       "id": "1056",
#       "assunto": "Visita T\u00e9cnica - Sem Conex\u00e3o Loss"
#     },
#     {
#       "id": "14",
#       "assunto": "Suporte T\u00e9cnico"
#     }
#   ]
# }

# query: "14,1056" tem que ser uma variavel, pode receber mais de um valor, esses id's vão vir da consulta O.S Por setor id_assunto."


# Cidade por ID
###
POST https://crm.tubaron.net/webservice/v1/cidade
Authorization: Basic token
ixcsoft:listar
Content-Type: application/json

{
    "qtype": "cidade.id",
    "query": "4660", 
    "oper": "IN",
    "page": "1",
    "op": "20"
}

#Retorno
# {
#   "page": "1",
#   "total": "1",
#   "registros": [
#     {
#        "id": "4660",
#        "nome": "Buti\u00e1",
#     }
#   ]
# }

# query: "4660" tem que ser uma variavel, pode receber mais de um valor, esses id's vão vir da consulta O.S Por setor id_cidade."


# colaborador por ID
###
POST https://crm.tubaron.net/webservice/v1/funcionarios
Authorization: Basic 44:82225522c68ce028c0652e38ccbade6ac43df33110853ec131ad1797aa1db656
ixcsoft:listar
Content-Type: application/json

{
    "qtype": "funcionarios.id",
    "query": "20", 
    "oper": "IN",
    "page": "1",
    "op": "20"
}

#Retorno
# {
#   "page": "1",
#   "total": "1",
#   "registros": [
#     {
#        "id": "20",
#        "funcionario": "VAGNER DA SILVA RODRIGUES ",
#     }
#   ]
# }

# query: "20" tem que ser uma variavel, pode receber mais de um valor, esses id's vão vir da consulta O.S Por setor id_tecnico."


# na page dashboard dever ser reconstruidas e ser representada em graficos ultilizando as consultas acima de forma que:
# - O.S Por assundo seja um grafico de pizza com a porcentagem de O.S por assunto e uma legenda ao lado com o nome de cada assunto.
# - O.S Por setor pode ser um card no fim da pagina com total somatoria de todas as consultas.
# - O.S Por colaborador pode ser um grafico de barras com a quantidade de O.S por colaborador e uma legenda ao lado com o nome de cada colaborador.
# - O.S Por cidade pode ser um grafico de pizza com a porcentagem de O.S por cidade e uma legenda ao lado com o nome de cada cidade.

#crie um filtro de data inicial e final na dashboard, que vai ser utilizado em todas as consultas, e deve ser uma variavel que pode receber mais de um valor, esses id's vão vir da consulta O.S Por setor id_cidade, id_assunto, id_tecnico, e deve contar um filtro de data inicial e final na dashboard.

# crie uma page separada para administração de usuario e grupo.

# crie uma nav bar na page de dashboard com o  nome da sessão e com o botao se logout, coloque o titulo de BI para monitoramento de produtividade de O.S.
# crie tambem um filtro para dados para um coloborador especifico, que vai ser utilizado em todas as consultas, e deve ser uma variavel que pode receber mais de um valor, esses id's vão vir da consulta O.S Por setor id_tecnico.
# crie tambem um filtro mensal.

# deixa um espaco para o logo na navibar pode deixar pronto para receber uma imagem com o nome de logo.png pasta public do frontend.