version: '3.8'

services:
  # Database MySQL
  mysql:
    image: mysql:8.0
    container_name: dashboard-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dashboard_orders
      MYSQL_USER: dashboard_user
      MYSQL_PASSWORD: dashboard_pass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - dashboard-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Backend NestJS
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: dashboard-backend-dev
    environment:
      NODE_ENV: development
      DATABASE_URL: "mysql://dashboard_user:dashboard_pass123@mysql:3306/dashboard_orders"
      JWT_SECRET: dev-jwt-secret-key-change-in-production
      PORT: 3001
      FRONTEND_URL: "http://localhost:3000"
      EXTERNAL_API_URL: ${EXTERNAL_API_URL:-http://localhost:8000}
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql
    networks:
      - dashboard-network
    restart: unless-stopped

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: dashboard-frontend-dev
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_APP_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - dashboard-network
    restart: unless-stopped
    command: npm run dev

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: dashboard-phpmyadmin-dev
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: dashboard_user
      PMA_PASSWORD: dashboard_pass123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - dashboard-network
    restart: unless-stopped

volumes:
  mysql_dev_data:
    driver: local

networks:
  dashboard-network:
    driver: bridge
